<a href="https://colab.research.google.com/github/mtzwyu/HaManhTruong_2045240326/blob/main/BTTL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Viết chương trình nhập vào 2 giá trị a, b và tính tổng, hiệu, tích thương của a và b.
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
print(f"Tổng = {a+b}, Hiệu = {a-b}, Tích = {a*b}, Thương = {a/b}")

Nhập a: 3
Nhập b: 4
Tổng = 7, Hiệu = -1, Tích = 12, Thương = 0.75


In [ ]:
# Bài 2: Lấy các ký tự từ chỉ số 2 đến chỉ số 4 (llo) của chuỗi “Hello World”
str = "Hello World"
print(str[2:5])

llo


In [ ]:
# Bài 3: Xóa khoảng trắng thừa ở đầu và cuối chuỗi “ Hello World ”. Chuyển chuỗi sang dạng hoa và thường. Thay ký tự H thành ký tự J.
str = "Hello World"
print(str.upper())
print(str.lower())
print(str.replace("H", "J"))

HELLO WORLD
hello world
Jello World


In [ ]:
# 4. In ra “Hello World!” nếu a lớn hơn b.
str = "Hello World!"
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
if a > b:
  print(str)
else:
  print("a nhỏ hơn b!")

Nhập a: 3
Nhập b: 4
a nhỏ hơn b!


In [ ]:
# 5. In ra “Yes” nếu a bằng b, ngược lại in “No”.
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
if a == b: print("Yes")
else: print("No")

Nhập a: 5
Nhập b: 6
No


In [ ]:
# 6. In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại.
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
if a == b: print(1)
elif a > b: print(2)
else: print(3)

Nhập a: 7
Nhập b: 8
3


In [ ]:
# 7. In ra “Hello World!” nếu a bằng b và b bằng d.
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
d = int(input("Nhập d: "))
if a == b and b == d: print("Hello World!")

Nhập a: 5
Nhập b: 6
Nhập d: 7


In [ ]:
# 8. In ra “Hello World!” nếu a bằng b hoặc c bằng d
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
c = int(input("Nhập c: "))
d = int(input("Nhập d: "))
if a == b or c == d: print("Hello World!")

Nhập a: 8
Nhập b: 5
Nhập c: 3
Nhập d: 5


In [ ]:
# 9. Viết lại câu lệnh if … else sau lên cùng 1 dòng.
result = "Yes" if a > b else "No"
print(result)

Yes


In [ ]:
# 10. Nhập vào 2 số a, b. Thực hiện câu lệnh và cho biết kết quả
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
print("A") if a > b else print("=") if a == b else print("B")

Nhập a: 2
Nhập b: 3
B


In [ ]:
# 11. Tạo mảng số nguyên a với n phần tử và mảng b chỉ chứa các phần tử chẵn của a.
import numpy as np
n = int(input("Nhập n: "))
a = np.arange(n)
print(a)
b = a[a % 2 == 0]
print(b)

Nhập n: 5
[0 1 2 3 4]
[0 2 4]


In [ ]:
# 12. Viết chương trình tính tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5.
sum = 0
for i in range(1000):
  if i % 3 ==0 or i % 5 == 0:
    sum+= i
print(sum)


233168


In [ ]:
# 13. Viết hàm trộn 2 mảng một chiều thành 1 mảng một chiều với mỗi phần tử của mảng mới là tổng của 2 phần tương ứng từ 2 mảng cho trước.
#     Trong quá trình trộn 2 mảng nếu mảng nào còn phần tử thì các phần tử còn lại của mảng đó sẽ đưa vào mảng mới.
# Ví dụ:
# Mảng a: 3 9 1 4
# Mảng b: 2 7 4 3 2 8
# Mảng kết quả: 5 16 5 7 2 8 23.
import numpy as np
a = np.array([3, 9, 1, 4])
b = np.array([2, 7, 4, 3, 2, 8])
def merge_and_sum_arrays(arr1, arr2):
    len1 = len(arr1)
    len2 = len(arr2)
    max_len = max(len1, len2)
    result_array = []

    for i in range(max_len):
        val1 = arr1[i] if i < len1 else 0
        val2 = arr2[i] if i < len2 else 0
        if i < len1 and i < len2:
            result_array.append(val1 + val2)
        elif i < len1:
            result_array.append(val1)
        elif i < len2:
            result_array.append(val2)
    return np.array(result_array)

c = merge_and_sum_arrays(a, b)
print(c)


[ 5 16  5  7  2  8]


In [ ]:
import numpy as np
import random
# 14
# a. Tạo mảng a chứa các số nguyên ngẫu nhiên
def tao_mang(m, n, min_val=-100, max_val=100):
    """Tạo mảng 2 chiều m x n với các số nguyên ngẫu nhiên trong [min_val, max_val]"""
    a = np.random.randint(min_val, max_val + 1, size=(m, n))
    return a

# b. Xuất các phần tử thuộc dòng k
def xuat_dong(a, k):
    """Xuất các phần tử trên dòng k (chỉ số bắt đầu từ 0)"""
    if 0 <= k < a.shape[0]:
        return a[k, :]
    return None

# c. Xuất các phần tử thuộc cột k
def xuat_cot(a, k):
    """Xuất các phần tử trên cột k (chỉ số bắt đầu từ 0)"""
    if 0 <= k < a.shape[1]:
        return a[:, k]
    return None

# d. Tìm dòng có tổng lớn nhất
def tim_dong_tong_lon_nhat(a):
    """Tìm dòng có tổng lớn nhất"""
    if a.size == 0:
        return -1, 0

    tong_cac_dong = np.sum(a, axis=1)
    dong_max = np.argmax(tong_cac_dong)
    tong_max = tong_cac_dong[dong_max]

    return dong_max, tong_max

# e. Tìm cột có tích nhỏ nhất
def tim_cot_tich_nho_nhat(a):
    """Tìm cột có tích nhỏ nhất"""
    if a.size == 0:
        return -1, 0

    # Tính tích từng cột
    tich_cac_cot = np.prod(a, axis=0)
    cot_min = np.argmin(tich_cac_cot)
    tich_min = tich_cac_cot[cot_min]

    return cot_min, tich_min

# f. Xuất các phần tử thuộc dòng chẵn và cột lẻ
def xuat_dong_chan_cot_le(a):
    """Xuất các phần tử ở dòng chỉ số chẵn và cột chỉ số lẻ"""
    if a.size == 0:
        return np.array([])

    # Lấy các dòng có chỉ số chẵn và cột có chỉ số lẻ
    ket_qua = a[::2, 1::2]  # ::2: lấy dòng chẵn, 1::2: lấy cột lẻ
    return ket_qua

# g. Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ
def tbc_chan_dong_le(a):
    """Tính trung bình cộng các số chẵn ở dòng lẻ"""
    if a.size == 0:
        return 0

    # Lấy các dòng lẻ
    dong_le = a[1::2, :]

    # Lấy các phần tử chẵn
    phan_tu_chan = dong_le[dong_le % 2 == 0]

    if len(phan_tu_chan) == 0:
        return 0

    return np.mean(phan_tu_chan)

# h. Tính trung bình cộng các phần tử thuộc biên
def tbc_bien(a):
    """Tính trung bình cộng các phần tử ở biên của mảng"""
    if a.size == 0:
        return 0

    m, n = a.shape

    if m == 1 and n == 1:
        return a[0, 0]

    # Lấy các phần tử biên
    bien = []

    # Dòng đầu và dòng cuối
    bien.append(a[0, :])      # dòng đầu
    if m > 1:
        bien.append(a[-1, :])   # dòng cuối

    # Cột đầu và cột cuối (bỏ qua các góc đã được lấy ở dòng đầu và dòng cuối)
    if n > 1:
        if m > 2:
            bien.append(a[1:-1, 0])   # cột đầu (không tính góc)
        if m > 2:
            bien.append(a[1:-1, -1])  # cột cuối (không tính góc)

    # Nối tất cả các phần tử biên
    bien_array = np.concatenate(bien) if bien else np.array([])

    return np.mean(bien_array) if len(bien_array) > 0 else 0

# i. Tính trung bình cộng các phần tử không thuộc biên
def tbc_khong_bien(a):
    """Tính trung bình cộng các phần tử không thuộc biên"""
    if a.size == 0:
        return 0

    m, n = a.shape

    # Nếu mảng có ít hơn 3 dòng hoặc 3 cột thì không có phần tử nào không thuộc biên
    if m <= 2 or n <= 2:
        return 0

    # Lấy phần bên trong (bỏ biên)
    khong_bien = a[1:-1, 1:-1]

    return np.mean(khong_bien)

# Hàm in mảng (tiện cho việc kiểm tra)
def in_mang(a):
    """In mảng 2 chiều"""
    if a.size == 0:
        print("Mảng rỗng")
        return

    print("Mảng:")
    print(a)
    print()

# Hàm main để kiểm tra
def main():
    # Nhập kích thước mảng
    m = int(input("Nhập số dòng m: "))
    n = int(input("Nhập số cột n: "))

    # a. Tạo mảng
    a = tao_mang(m, n, -50, 50)
    in_mang(a)

    # b. Xuất dòng k
    k = int(input(f"\nNhập dòng cần xuất (0 đến {m-1}): "))
    dong = xuat_dong(a, k)
    if dong is not None:
        print(f"Dòng {k}: {dong}")
    else:
        print("Dòng không hợp lệ!")

    # c. Xuất cột k
    k = int(input(f"\nNhập cột cần xuất (0 đến {n-1}): "))
    cot = xuat_cot(a, k)
    if cot is not None:
        print(f"Cột {k}: {cot}")
    else:
        print("Cột không hợp lệ!")

    # d. Tìm dòng có tổng lớn nhất
    dong_max, tong_max = tim_dong_tong_lon_nhat(a)
    print(f"\nDòng có tổng lớn nhất: dòng {dong_max} với tổng = {tong_max}")

    # e. Tìm cột có tích nhỏ nhất
    cot_min, tich_min = tim_cot_tich_nho_nhat(a)
    print(f"Cột có tích nhỏ nhất: cột {cot_min} với tích = {tich_min}")

    # f. Xuất phần tử thuộc dòng chẵn và cột lẻ
    ket_qua_f = xuat_dong_chan_cot_le(a)
    print(f"\nCác phần tử ở dòng chẵn và cột lẻ:")
    if ket_qua_f.size > 0:
        print(ket_qua_f)
    else:
        print("  Không có phần tử nào!")

    # g. Tính trung bình cộng các phần tử chẵn ở dòng lẻ
    tbc_g = tbc_chan_dong_le(a)
    print(f"\nTrung bình cộng các phần tử chẵn ở dòng lẻ: {tbc_g:.2f}")

    # h. Tính trung bình cộng các phần tử biên
    tbc_h = tbc_bien(a)
    print(f"Trung bình cộng các phần tử biên: {tbc_h:.2f}")

    # i. Tính trung bình cộng các phần tử không thuộc biên
    tbc_i = tbc_khong_bien(a)
    print(f"Trung bình cộng các phần tử không thuộc biên: {tbc_i:.2f}")

# Chạy chương trình
if __name__ == "__main__":
    main()

Nhập số dòng m: 3
Nhập số cột n: 4
Mảng:
[[-17   8 -39  15]
 [-12  10  39  -7]
 [ 29  14  46 -18]]


Nhập dòng cần xuất (0 đến 2): 2
Dòng 2: [ 29  14  46 -18]

Nhập cột cần xuất (0 đến 3): 2
Cột 2: [-39  39  46]

Dòng có tổng lớn nhất: dòng 2 với tổng = 71
Cột có tích nhỏ nhất: cột 2 với tích = -69966

Các phần tử ở dòng chẵn và cột lẻ:
[[  8  15]
 [ 14 -18]]

Trung bình cộng các phần tử chẵn ở dòng lẻ: -1.00
Trung bình cộng các phần tử biên: 1.90
Trung bình cộng các phần tử không thuộc biên: 24.50


In [ ]:
class SINHVIEN:
    def __init__(self, mSV, Name:str, ns:int, dtb:float):
        self.MaSV = mSV
        self.Name = Name
        self.NamSinh = ns
        self.DTB = dtb

    def dk_len_lop(self):
        """Kiểm tra điều kiện lên lớp"""
        return True if self.DTB >= 5 else False
    def SV_du_tuoi_20(self):
        """Kiem tra SV nao du 20 tuoi"""
        return 2026 - self.NamSinh >= 20
    def SV_DH(self):
        """Kiem tra SV nào thuộc bậc đại học"""
        # Hệ DH có mã sinh viên chứa 2 ký tự DH ở vị trí 2,3 (index 2:4)
        return "DH" in self.MaSV[2:4]
    def SV_Ten_Lan(self):
        """Kiểm tra SV nào có tên Lan"""
        parts = self.Name.strip().split()
        return True if parts and parts[-1] == 'Lan' else False
    def SV_Ho_Phan(self):
        """Kiểm tra SV nào có họ Phan"""
        parts = self.Name.strip().split()
        return True if parts and parts[0] == 'Phan' else False
    def __str__(self):
        """Hiển thị thông tin sinh viên"""
        return f"MSV: {self.MaSV}, Tên: {self.Name}, Năm sinh: {self.NamSinh}, ĐTB: {self.DTB}"

def main():
    # b. Cho một mảng có n sinh viên.
    danh_sach_sv = []

    # Thêm sinh viên vào mảng
    danh_sach_sv.append(SINHVIEN("02DH0001", "Nguyen Thi Lan", 2000, 8.5))
    danh_sach_sv.append(SINHVIEN("02CD0002", "Phan Van A", 2001, 4.5))
    danh_sach_sv.append(SINHVIEN("02DH0003", "Tran Thi Lan", 2002, 7.0))
    danh_sach_sv.append(SINHVIEN("02DH0004", "Phan Thi B", 2003, 9.0))
    danh_sach_sv.append(SINHVIEN("02CD0005", "Le Van Lan", 2004, 5.5))
    danh_sach_sv.append(SINHVIEN("02DH0006", "Nguyen Van C", 2005, 6.5))
    danh_sach_sv.append(SINHVIEN("02DH0007", "Phan Thi Lan", 2004, 7.8))
    danh_sach_sv.append(SINHVIEN("02CD0008", "Hoang Thi D", 2003, 8.0))

    # c. Số sinh viên đủ điều kiện lên lớp (DTB >= 5)
    sv_len_lop = [sv for sv in danh_sach_sv if sv.dk_len_lop()]
    print(f"Số lượng sinh viên đủ đk lên lớp: {len(sv_len_lop)}")

    # d. Xuất các sinh viên đủ 20 tuổi
    print("\n=== SINH VIÊN ĐỦ 20 TUỔI ===")
    for sv in danh_sach_sv:
        if sv.SV_du_tuoi_20():
            print(sv)

    # e. Đếm số sinh viên học hệ đại học (DH ở vị trí 2,3)
    sv_dh = [sv for sv in danh_sach_sv if sv.SV_DH()]
    print(f"\nSố sinh viên hệ Đại học: {len(sv_dh)}")

    # f. Số sinh viên có tên «Lan»
    sv_lan = [sv for sv in danh_sach_sv if sv.SV_Ten_Lan()]
    print(f"Số sinh viên có tên 'Lan': {len(sv_lan)}")

    # g. Số sinh viên có họ «Phan»
    sv_phan = [sv for sv in danh_sach_sv if sv.SV_Ho_Phan()]
    print(f"Số sinh viên có họ 'Phan': {len(sv_phan)}")

if __name__ == "__main__":
    main()

Số lượng sinh viên đủ đk lên lớp: 7

=== SINH VIÊN ĐỦ 20 TUỔI ===
MSV: 02DH0001, Tên: Nguyen Thi Lan, Năm sinh: 2000, ĐTB: 8.5
MSV: 02CD0002, Tên: Phan Van A, Năm sinh: 2001, ĐTB: 4.5
MSV: 02DH0003, Tên: Tran Thi Lan, Năm sinh: 2002, ĐTB: 7.0
MSV: 02DH0004, Tên: Phan Thi B, Năm sinh: 2003, ĐTB: 9.0
MSV: 02CD0005, Tên: Le Van Lan, Năm sinh: 2004, ĐTB: 5.5
MSV: 02DH0006, Tên: Nguyen Van C, Năm sinh: 2005, ĐTB: 6.5
MSV: 02DH0007, Tên: Phan Thi Lan, Năm sinh: 2004, ĐTB: 7.8
MSV: 02CD0008, Tên: Hoang Thi D, Năm sinh: 2003, ĐTB: 8.0

Số sinh viên hệ Đại học: 5
Số sinh viên có tên 'Lan': 4
Số sinh viên có họ 'Phan': 3
